### ISSUE TITLE
missing cython requirement

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#127] opened 2018-01-10 18:20 UTC
```
>python.exe -m pip install mdfreader
Collecting mdfreader
  Downloading mdfreader-2.7.4.tar.gz (653kB)
    100% |████████████████████████████████| 655kB 655kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Daniel\AppData\Local\Temp\pip-build-i93z7xpm\mdfreader\setup.py", line 6, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
```

**Comment by ratal** [comment] 2018-01-10 22:08
I do not reproduce your issue. I will check later on windows.
Are you sure your config is ok because looking at Cython tutorial, I have exact same line for cythonize import ?
[](http://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html)

**Comment by danielhrisca** [comment] 2018-01-11 01:42
Try with a Python installation or virtualenv that does not have cython already installed

**Comment by ratal** [comment] 2018-01-11 11:03
cython is normally a requirement for mdfreader but you want to propose it as an optionnal requirement ?

**Comment by danielhrisca** [comment] 2018-01-11 11:18
Actually the problem is if you need _cython_ during the installation, and _cython_ is not already installed, you will get the error even though _cython_ is included in the _install_requires_

This probably helps:
http://cython.readthedocs.io/en/latest/src/reference/compilation.html?highlight=compilation#distributing-cython-modules

**Comment by ratal** [comment] 2018-01-12 21:13
Thanks Daniel for the tip.
I think on linux, there is no issue installing cython and have correct compilation environment.
But on windows, most difficult is probably to have suitable compilation environment rather than installing cython. Do you experiment and want to include it in asammdf for performance up ?

**Comment by danielhrisca** [comment] 2018-01-12 21:29
It's a real pain in the ass to get the compilation working in Windows, this is why I normally reply on WinPython and https://www.lfd.uci.edu/~gohlke/pythonlibs/ , and I will just use _numpy_ without custom _cython_ or C extensions for asammdf.

Like I said the cython issue came when I had to use a stripped down Pyhon installation that did not have cython installed (WinPyhton 3.7.0 in this particular case)

**Comment by ratal** [comment] 2018-01-18 22:21
Doing the same for windows but using anaconda. For big files (several Gb), I think cython is worth the pain for mdfreader.
Should be ok now, closing but reopen if you face again this issue.

**Comment by ratal** [comment] 2018-05-18 21:35
Thanks, I remove all import in header and made sure it woudl install without cython, in dev branch

**Comment by danielhrisca** [comment] 2018-05-23 12:25
```
daniel@daniel-VirtualBox:~$ pip3 install cython
Collecting cython
  Downloading https://files.pythonhosted.org/packages/19/eb/c4d9f3beafd5ac0615936860bcee41d93ca58f8734a16715da0037d2c468/Cython-0.28.2-cp36-cp36m-manylinux1_x86_64.whl (3.4MB)
    100% |████████████████████████████████| 3.4MB 398kB/s 
Installing collected packages: cython
Successfully installed cython-0.28.2
daniel@daniel-VirtualBox:~$ pip3 install https://github.com/ratal/mdfreader/archive/dev.zip
Collecting https://github.com/ratal/mdfreader/archive/dev.zip
  Downloading https://github.com/ratal/mdfreader/archive/dev.zip
     / 450kB 706kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 346, in get_provider
        module = sys.modules[moduleOrReq]
    KeyError: 'numpy'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-zkevh2nd-build/setup.py", line 9, in <module>
        numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1136, in resource_filename
        return get_provider(package_or_requirement).get_resource_filename(
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 348, in get_provider
        __import__(moduleOrReq)
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-zkevh2nd-build/
```

**Comment by AkbarAlam** [comment] 2018-05-29 11:56
I have tried to install and still have this problem. any solution?

**Comment by ratal** [comment] 2018-05-30 21:42
Hi Daniel,
I guess you have this error because there is no numpy installed in your virtual environment, completly virgin except Cython ?
I looked a bit and coud not find any other way than just informing user he should install numpy. Normally pip should handle this depency but with this code, it is not possible I think; I need those include_dirs and if numpy is not installed I do not know how to request numpy install.

**Comment by ratal** [comment] 2018-05-30 21:46
Hi Gourab,
I guess your issue is the one described at the beginning of this thread. Did you try installing the git dev branch ?

**Comment by cristi-neagu** [comment] 2018-05-31 07:36
Could this work?
https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires

**Comment by danielhrisca** [comment] 2018-05-31 08:17
@cristi-neagu 
https://github.com/ratal/mdfreader/blob/dev/setup.py#L76

**Comment by AkbarAlam** [comment] 2018-06-01 10:51
@ratal  yeah . but  getting this error `error: Setup script exited with error: Unable to find vcvarsall.bat`

**Comment by ratal** [comment] 2018-06-01 14:26
Hi,
I think this is different issue (here about how to install mdfreader without cython installed)
You are trying to build dataRead cython (you probably installed) module but you are missing Microsoft Visual C++ Compiler for you installed Python version.
Up to you, either install with (need proper compilation environment) or without cython (pure python)

**Closed** 2018-10-18 16:17 UTC
Labels: Waiting fix confirmation
